# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "lane for android firebase Distribute app"
  lane :firebase_distribute  do
      sh "flutter clean"
      sh "flutter build apk --release"
     release = firebase_app_distribution(
                  app: "1:546106504523:android:ab55c6ad713719f3ae24ce",
                  firebase_cli_token:ENV['firebase_cli_token'],
                  android_artifact_type:"APK",
                  testers: "abdofekryasda@gmail.com",
                  android_artifact_path:"../build/app/outputs/flutter-apk/app-release.apk",
                  release_notes: "Lots of amazing new features to test out!"
              )

  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
